# The URL the site will be built for
base_url = "https://blog.cielago.xyz" 

#theme = "apollo"
#theme = "after-dark"
theme = "archie-zola"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true


[extra]
theme = "auto"
toc = true
socials = [
  # Configure socials here
]
menu = [
  # Configure menu bar here ( not used by Archie 
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/about", url = "/about", weight = 3 },
  { name = "/tags", url = "/tags", weight = 4 },
  { name = "/tech_notes", url = "/tech_notes", weight = 1 },
]

# --------------------------------
# Archie config
mode = "toggle"

# subtitle will show under the title in index page
subtitle = "Technical blog covering various topics, including finance, crypto, developer tooling, and more."

favicon = "/icon/favicon.png"

# show in the footer
copyright = "Ian"

[extra.translations]
languages = [{name = "en", url = "/"}]

# config multi-language menu and other text
[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "Home", url = "/", weight = 2 },
    { name = "All posts", url = "/posts", weight = 2 },
    { name = "About", url = "/about", weight = 3 },
    { name = "Tags", url = "/tags", weight = 4 },
    { name = "Tech Notes", url = "/tech_notes", weight = 5 },
]

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://x.com/CryptoJ97019913/"
# ----
# Put all your custom variables here
